[workspace]
members = ["decoder", "parser", "examples/stdin"]
resolver = "2"

[workspace.package]
authors = ["Tal Risin <tal@risin.dev>"]
edition = "2021"
keywords = ["cdefmt", "defmt"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/risint96/cdefmt"
version = "0.7.0"
